/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboardmotor;

import java.awt.event.MouseAdapter;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.awt.event.*;
import javax.swing.*;

/**
 *
 * @author fa
 */
public class MainDashboard extends javax.swing.JFrame {

    int Gear = 0, max, rpm;
    Timer gasPlus = new Timer(90, new ActionListener() {   
        @Override
        public void actionPerformed(ActionEvent e) {
            int up = Integer.parseInt(txfSpeed.getText());
            switch(Gear) {
                case 1: max = 20; break;
                case 2: max = 40; break;
                case 3: max = 80; break;
                case 4: max = 140; break;
            }
            
            if (up < max) {
                up++;
            }
            
            rpm = up / max * 1000;
            
            txfRpm.setText(String.valueOf(rpm));
            txfSpeed.setText(String.valueOf(up));
        }
    });
    
    Timer gasMinus = new Timer(600, new ActionListener() {       
        @Override
        public void actionPerformed(ActionEvent e) {
        int up = Integer.parseInt(txfSpeed.getText());    
            if (up > 0) {
                up--;
            }  
            
            rpm = up / max * 1000;
            
            txfRpm.setText(String.valueOf(rpm));
            txfSpeed.setText(String.valueOf(up));
        }
    });
    
    Timer rem = new Timer(150, new ActionListener() {       
        @Override
        public void actionPerformed(ActionEvent e) {
        int up = Integer.parseInt(txfSpeed.getText());    
            if (up > 0) {
                up--;
            }     
            
            rpm = up / max * 1000;
            
            txfRpm.setText(String.valueOf(rpm));
            txfSpeed.setText(String.valueOf(up));
        }
    });
    
    public MainDashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnUp = new javax.swing.JButton();
        btnDown = new javax.swing.JButton();
        btnGas = new javax.swing.JButton();
        btnRem = new javax.swing.JButton();
        tglOnOff = new javax.swing.JToggleButton();
        lblGear = new javax.swing.JLabel();
        txfGear = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txfSpeed = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txfRpm = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnUp.setText("Up");
        btnUp.setEnabled(false);
        btnUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnUpMouseClicked(evt);
            }
        });
        btnUp.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnUpKeyPressed(evt);
            }
        });

        btnDown.setText("Down");
        btnDown.setEnabled(false);
        btnDown.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDownMouseClicked(evt);
            }
        });

        btnGas.setText("Gas");
        btnGas.setEnabled(false);
        btnGas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnGasMousePressed(evt);
            }
        });
        btnGas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGasActionPerformed(evt);
            }
        });
        btnGas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                btnGasKeyPressed(evt);
            }
        });

        btnRem.setText("Rem");
        btnRem.setEnabled(false);
        btnRem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                btnRemMousePressed(evt);
            }
        });

        tglOnOff.setText("Hidupkann");
        tglOnOff.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                tglOnOffItemStateChanged(evt);
            }
        });

        lblGear.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblGear.setText("Gear");

        txfGear.setEditable(false);
        txfGear.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        txfGear.setText("0");
        txfGear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txfGearActionPerformed(evt);
            }
        });

        jLabel1.setText("Speed Km/h");

        txfSpeed.setEditable(false);
        txfSpeed.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        txfSpeed.setText("0");

        jLabel2.setText("RPM");

        txfRpm.setEditable(false);
        txfRpm.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDown, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnUp)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(txfSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tglOnOff)
                                .addGap(38, 38, 38))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(btnRem, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(btnGas))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblGear)
                                            .addGap(130, 130, 130)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(txfGear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 17, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(144, 144, 144)
                                .addComponent(txfRpm, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel2)
                        .addGap(39, 39, 39))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txfGear, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txfSpeed, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txfRpm, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUp)
                    .addComponent(tglOnOff))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnRem)
                    .addComponent(btnDown)
                    .addComponent(btnGas))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tglOnOffItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_tglOnOffItemStateChanged
        int state = evt.getStateChange();
        if (state == java.awt.event.ItemEvent.SELECTED) {
            tglOnOff.setText("Matikan");
            btnUp.setEnabled(true);
            btnDown.setEnabled(true);
            btnRem.setEnabled(true);
            btnGas.setEnabled(true);
        } else {
            tglOnOff.setText("Hidupkan");
            btnUp.setEnabled(false);
            btnDown.setEnabled(false);
            btnRem.setEnabled(false);
            btnGas.setEnabled(false);
        }
    }//GEN-LAST:event_tglOnOffItemStateChanged

    private void btnGasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnGasActionPerformed

    private void txfGearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txfGearActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txfGearActionPerformed

    private void btnUpKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnUpKeyPressed
        
    }//GEN-LAST:event_btnUpKeyPressed

    private void btnUpMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnUpMouseClicked
        Gear = Integer.parseInt(txfGear.getText());
        if (Gear < 4) {
            Gear++;
        }
        txfGear.setText(String.valueOf(Gear));
    }//GEN-LAST:event_btnUpMouseClicked

    private void btnDownMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDownMouseClicked
        Gear = Integer.parseInt(txfGear.getText());
        if (Gear > 0) {
            Gear--;
        }
        txfGear.setText(String.valueOf(Gear));
    }//GEN-LAST:event_btnDownMouseClicked

    private void btnGasMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnGasMousePressed
        
        btnGas.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {           
                gasMinus.stop();
                gasPlus.start();
            }

            @Override
            public void mouseReleased(MouseEvent e) {
              gasPlus.stop();
              gasMinus.start();
            }
        });    
        
        
    }//GEN-LAST:event_btnGasMousePressed

    private void btnGasKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_btnGasKeyPressed
       
    }//GEN-LAST:event_btnGasKeyPressed

    private void btnRemMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRemMousePressed
        btnRem.addMouseListener(new MouseAdapter() {
            @Override
            public void mousePressed(MouseEvent e) {
//                
                rem.start();
            }

            @Override
            public void mouseReleased(MouseEvent e) {
           
              rem.stop();
            }
        });
    }//GEN-LAST:event_btnRemMousePressed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        
       /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainDashboard().setVisible(true);
        
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDown;
    private javax.swing.JButton btnGas;
    private javax.swing.JButton btnRem;
    private javax.swing.JButton btnUp;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel lblGear;
    private javax.swing.JToggleButton tglOnOff;
    private javax.swing.JTextField txfGear;
    private javax.swing.JTextField txfRpm;
    private javax.swing.JTextField txfSpeed;
    // End of variables declaration//GEN-END:variables

   
}
